### ISSUE TITLE
Remote ssh tunnel

### ISSUE THREAD

**Issue by pulquero** [flaupretre/terraform-ssh-tunnel#11]
Feature request for remote ssh tunnel support. That is, ssh to a host and set up a ssh -L tunnel to a database. db_tunnel host and port will then be that of the ssh host rather than localhost.

**Comment by flaupretre** [comment]
I am not sure I understand what you mean. We already open an ssh connection to a gateway host, which opens another connection to the final target. Do you mean we could have two gateways chained together ?

If you look look at the SSH documentation, you will read that, when using '-L', the connection to 'host:hostport' is done from the remote (gateway) machine, not from the local one. So, IMHO, we already have what you suggest : SSH connection from localhost:local_port to gateway_host:gateway_port and, then, another connection (not SSH) from gateway_host to target_host:target_port.

**Comment by pulquero** [comment]
I mean the "reverse": non-SSH to gateway_host, then SSH tunnel to target_host, i.e. make the gateway a proxy for the target. Imagine the cmd line something like:
ssh gateway_host "ssh -L gateway_host:gateway_port:target_host:target_port target_host"
Requiring that localhost has the key for gateway_host, and gateway_host has the key for target_host. Use case is gateway is sitting in virtual net 1, target is sitting in virtual net 2, peered to virtual net 1. Localhost is on-premise with access to virtual net 1.

**Comment by flaupretre** [comment]
I am sorry but I don't understand what you mean. What you describe cannot work as it will use target_host as a gateway to itself. I think what you want is exactly what I provide : a remote SSH tunnel.
