### ISSUE TITLE
Unable to use the provider

### ISSUE THREAD

**Issue by pankajpantkappa** [flaupretre/terraform-ssh-tunnel#16]
Hi, 

I am trying to implement the provider, but once i put following code 

`module db_tunnel {
  # You can also retrieve this module from the terraform registry
  source       = "flaupretre/tunnel/ssh"
  version      = "1.9.0"

  target_host  = resource.aws_db_instance.test.endpoint
  target_port  = 54320

  gateway_host = module.ec2_bastion.public_ip
}` 

I receives following error

`│ Error: External Program Execution Failed
│ 
│   with module.db_tunnel.data.external.ssh_tunnel,
│   on .terraform/modules/db_tunnel/main.tf line 11, in data "external" "ssh_tunnel":
│   11:   program = [
│   12:     var.shell_cmd,
│   13:     "${path.module}/tunnel.sh"
│   14:   ]
│ 
│ The data source received an unexpected error while attempting to execute the program.
│ 
│ Program: /opt/homebrew/bin/bash
│ Error Message: Child process (8425) failure - Aborting
│ Child diagnostics follow:
│ nohup: timeout: No such file or directory
│ 
│ State: exit status 1`

Can you please help me...

**Comment by flaupretre** [comment]
Yes, you need the 'timeout' command to be present in your environment. On MacOS, this is supposed to be provided by the 'coreutils' package.
