### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by dumptruckman** [flaupretre/terraform-ssh-tunnel#23]
I am attempting to use this module in conjunction with https://github.com/ljfranklin/terraform-resource in Concourse. However, the tunnel.sh script fails to run due to `Error Message: ps: unrecognized option: p`. From what I can tell, the `ps` command in Alpine does not have a `-p` option. Is it possible to for the script to not do all the process checking stuff and just use some dumb timeouts or something?

**Comment by flaupretre** [comment]
Supposed to be fixed in f2f1e7e. Please check.

**Comment by dumptruckman** [comment]
Thanks for the quick fix! I test it and it does appear to be working now on Concourse in an Alpine container.
