### ISSUE TITLE
Version 2.0.y isn't working under Linux

### ISSUE THREAD

**Issue by Bernd4242** [flaupretre/terraform-ssh-tunnel#28]
We have to connect trough a jumphost to login to PostgreSQL.
Version 1.13.0 works like a charm. 
Using 2.0.x versions connection fails and we don't get any debug-output for ssh anymore.

For tests we used ssh-agent and connection seems to be established, but following db-login fails.
![woUsingSshAgent](https://github.com/flaupretre/terraform-ssh-tunnel/assets/145662506/f76e12a7-0b68-4e16-b196-843bca6faf59)
![failingDbLogin](https://github.com/flaupretre/terraform-ssh-tunnel/assets/145662506/1c55de63-98e4-4ef3-93d7-bd942387303a)

Tested this in Arch-Linux/bash, Docker Alpine-Image/bash, Docker Hashicorp/terraform image.
It works on MacOS.

**Comment by sashasimkin** [comment]
For those who might come to this - I had the same problem with 2.0.0. Tried to downgrade to 1.13.0 as OP suggested, but didn't help either.

When I tried to execute forwarding comment manually I saw this:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
*****
Please contact your system administrator.
Add correct host key in ***/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in ***/.ssh/known_hosts:740
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
******Port forwarding is disabled to avoid man-in-the-middle attacks.********
UpdateHostkeys is disabled because the host key is not trusted.
```

Doing `ssh-keygen -R {host}` fixed the issue.
