### ISSUE TITLE
what if existing connections with the same local mapping are forcefully closed once a new one opens 

### ISSUE THREAD

**Issue by wibed** [flaupretre/terraform-ssh-tunnel#33]
atm i consider a `local-exec` to fish out the process, close it and reopen another tunnel based on the circumstance
that tools arent as dynamically configurable as id like them to be.

some resource:
https://unix.stackexchange.com/questions/389014/getting-a-pid-for-an-ssh-process-that-backgrounded-itself

i monkey patched the terraform process accordingly:

```yaml
resource "null_resource" "worker1_tunnel_close" {
  depends_on = [ 
    talos_machine_configuration_apply.worker1
  ]

  provisioner "local-exec" {
    command = "pgrep -f \"ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -i ${var.proxmoxremotehostkeypath}\" | xargs kill"
  }
}
```

*it might be easier to attach a generated unique id to the process (is that even possible?) and fetch it like this*

**Comment by wibed** [comment]
a way to tell if the command has failed would be awesome as well.

maybe there is some overlap with this issue

**Comment by flaupretre** [comment]
Sorry, I don't understand the issue. Can you elaborate ?

**Comment by wibed** [comment]
ideally, i cant open multiple connections within the same session without making a separate call to look for it and close it explicitly.

it covers my use case for the moment. but have no time to work on this myself.
