### ISSUE TITLE
SSH using "kubectl" type example

### ISSUE THREAD

**Issue by felipelaptrin** [flaupretre/terraform-ssh-tunnel#41]
Hi,

Could you provide an example on how to use the SSH type "kubectl"?

I'm specially confused with the "target_host" and "target_port". 

The section [Kubernetes Port Forwarding](https://registry.terraform.io/modules/flaupretre/tunnel/ssh/latest#kubernetes-port-forwarding) explains that `gateway_host` and `gateway_port` argument, but I'm don't understand what should be the value for the `target_host` and `target_port`.

Thanks in advance

**Comment by flaupretre** [comment]
Actually, for the 'kubectl' gateway, 'gateway_port' and 'target_host' are ignored. As specified in the documentation 'gateway_host' contains the first argument for the 'port-foward' command ('pod/xxx', 'service/xxx', etc) and 'target_port' must be the port number we want to access on this object.
