### ISSUE TITLE
Error on apply : nohup: timeout: No such file or directory

### ISSUE THREAD

**Issue by RomainBillot** [flaupretre/terraform-ssh-tunnel#9]
Hi 👋 ,

I am trying to use the ssh tunnel module, which seems to be awesome for my use case btw ❤️ 

Here is how I configured it:

```tf
module "db_tunnel" {
  source  = "flaupretre/tunnel/ssh"
  version = "1.6.0"

  target_host = data.aws_db_instance.main.address
  target_port = data.aws_db_instance.main.port

  gateway_host = data.aws_instance.bastion.public_ip
  gateway_user = "ubuntu"

  ssh_cmd = "ssh -i ~/.ssh/bastion"
}

provider "postgresql" {
  alias    = "tunnel"
  scheme   = "awspostgres"
  host     = module.db_tunnel.host
  port     = module.db_tunnel.port
  username = "root"
  password = "notsecure"
  // superuser = false
}
```

Here is the `apply` output
```
│ Error: failed to execute "bash": Child process (28391) failure - Aborting
│ Child diagnostics follow:
│ nohup: timeout: No such file or directory
│ 
│ 
│   with module.db_tunnel.data.external.ssh_tunnel[0],
│   on .terraform/modules/db_tunnel/main.tf line 15, in data "external" "ssh_tunnel":
│   15: data external ssh_tunnel {
```

Is there something wrong here? 😢

**Comment by RomainBillot** [comment]
Looks like it was a mac issue.

`nohup` wasn't the 'real' nohup.

Instead, I used `gnohup`, which works for whatever reason. Thanks 🍎

**Comment by Ladvien** [comment]
Hello @RomainBillot,

Hate to bother, but could you explain a bit more how you used gnohup to get around this issue? Blocked here. Many thanks.

**Comment by flaupretre** [comment]
I'm also interested by a patch that would automatically switch to a 'nohup' alternative if it is found in the path, for instance. I'm sorry but I don't have access to a mac environment. So I can't do it by myself.
